[Service]
ExecStart=
ExecStart=-/usr/local/bin/tty-console.sh

Type=idle

StandardInput=tty-force
StandardOutput=tty
StandardError=tty

TTYPath=/dev/tty3
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes

Restart=always
RestartSec=1