#!/bin/bash

# Default DIR
DIR=$(pwd)


LIST_PROGS=false

for arg in "$@"; do
    case "$arg" in
        -f) DIR="/mnt/floppy" ;;
        -x) LIST_PROGS=true ;;
        *) ;;
    esac
done

echo -e "\e[47m\e[30m00 DIRECTORY CONTENTS\e[0m"

# List files
NUM=1
while IFS= read -r entry; do
    if [ "$LIST_PROGS" = true ] && [ ! -x "$DIR/$entry" ]; then
        continue
    fi

    # Determine type
    if [ -d "$DIR/$entry" ]; then
        TYPE="DIR"
        EXT="-"
        SIZE="-"
    elif [ -x "$DIR/$entry" ]; then
        TYPE="PRG"
        # Only use extension if it exists
        EXT="${entry##*.}"
        [ "$EXT" == "$entry" ] && EXT="-"
        SIZE=$(stat -c%s "$DIR/$entry")
    else
        TYPE="FILE"
        EXT="${entry##*.}"
        [ ${#EXT} -gt 5 ] && EXT="${EXT:0:5}"
        [ "$EXT" == "$entry" ] && EXT="-"
        SIZE=$(stat -c%s "$DIR/$entry")
    fi

    # Trim filename if too long
    FNAME=$(basename "$entry")
    [ ${#FNAME} -gt 20 ] && FNAME="${FNAME:0:20}"

    # Adjust spacing dynamically based on filename length
    FNAME_SPACES=$((22 - ${#FNAME}))
    [ $FNAME_SPACES -lt 2 ] && FNAME_SPACES=2
    SPACES=$(printf '%*s' "$FNAME_SPACES")

    printf "%02d %s%s %-6s %-8s %s\n" "$NUM" "$FNAME" "$SPACES" "$EXT" "$TYPE" "$SIZE"
    NUM=$((NUM + 1))
done < <(ls -A "$DIR")
